### ISSUE TITLE
`make-kdf` and the `digest` parameter

### ISSUE THREAD

**Issue by lovrolu** [sharplispers/ironclad#16]
When using the PBKDF algorithms with `make-kdf`, I would expect `digest` to accept either a keyword symbol or a symbol from the `ironclad` package, as is the convention for numerous other functions (`make-digest`, `make-cipher`, `make-mac`, etc.). However, it seems to only accept symbols from the `ironclad` package.

The documentation for `make-kdf` should also be improved to explicitly mention what `digest` should be.

**Comment by glv2** [comment]
Commit 0055c420a87e99afcc9de52574866613bac9ad6c should fix this bug.
Thanks for the report.

**Comment by lovrolu** [comment]
I've created a PR that clarifies the documentation as well. :-) See #17.

**Comment by glv2** [comment]
Merged, thanks.
