### ISSUE TITLE
HKDF

### ISSUE THREAD

**Issue by mgi** [sharplispers/ironclad#19]
Hi,

I'm in the process of adding hmac-kdf [RFC 5869](https://tools.ietf.org/html/rfc5869) to ironclad. So far so good, but I don't know what to do with the optional `info` vector.

Should I modify the `derive-key` interface to have it as a parameter? Should It be a slot into the new `hmac-kdf` class?

Thanks

**Comment by glv2** [comment]
The ```info``` vector seems to have the same role as the ```additional-data``` vector for *argon2*, therefore the ```additional-data``` keyword of the ```make-kdf``` function can be used.

I'd say:
 - Put a ```info``` slot in the ```hmac-kdf``` class.
 - In ```make-kdf```, initialize the ```info``` slot with the value of ```additional-data``` when instanciating the ```hmac-kdf``` class.
 - In ```shared-initialize```, check that the ```info``` slot will be set to a value that makes sense.
 - In ```derive-key```, fetch the ```info``` slot and do stuff with it.

Basically, it should be pretty similar to what is done with ```additional-data``` for the ```argon2``` class.

**Comment by glv2** [comment]
Implemented and merged (PR #20).
