### ISSUE TITLE
Ironclad (from quicklisp) will not compile

### ISSUE THREAD

**Issue by VK3FNG** [sharplispers/ironclad#25]
Quicklisp attempts to install Ironclad 0.47 but installation fails with:

Invalid number of arguments: 5

`  0: (SB-X86-64-ASM::|movzx| #<SB-ASSEM:SEGMENT :TYPE :REGULAR> #<SB-C::VOP :INFO NIBBLES:UB32REF/LE :ARGS #<SB-C:TN-REF :TN #<SB-C:TN IRONCLAD::INPUT-BLOCK1!1[RDI]> :WRITE-P NIL :VOP NIBBLES:UB32REF/LE> :..
  1: ((SB-C::VOP NIBBLES:UB32REF/LE) #<SB-C::VOP :INFO NIBBLES:UB32REF/LE :ARGS #<SB-C:TN-REF :TN #<SB-C:TN IRONCLAD::INPUT-BLOCK1!1[RDI]> :WRITE-P NIL :VOP NIBBLES:UB32REF/LE> :RESULTS #<SB-C:TN-REF :TN #..
  2: (SB-C::GENERATE-CODE #<SB-C:COMPONENT :NAME SB-IMPL::XSUBTRACT {1003B57163}>)
  3: (SB-C::%COMPILE-COMPONENT #<SB-C:COMPONENT :NAME SB-IMPL::XSUBTRACT {1003B57163}>)
  4: (SB-C::COMPILE-COMPONENT #<SB-C:COMPONENT :NAME SB-IMPL::XSUBTRACT {1003B57163}>)
  5: (SB-C::%COMPILE (SB-INT:NAMED-LAMBDA IRONCLAD::XOR-BLOCK (IRONCLAD:BLOCK-LENGTH IRONCLAD::INPUT-BLOCK1 IRONCLAD::INPUT-BLOCK1-START IRONCLAD::INPUT-BLOCK2 IRONCLAD::INPUT-BLOCK2-START IRONCLAD::OUTPUT..
  6: (SB-C::FOPCOMPILE-FUNCTION #<SB-FASL:FASL-OUTPUT "/home/matt/.cache/common-lisp/sbcl-1.3.14-linux-x64/home/matt/quicklisp/dists/quicklisp/software/ironclad-v0.47/src/common-TMP.fasl"> (SB-INT:NAMED-LA..
  7: (SB-C::FOPCOMPILE (SB-IMPL::%DEFUN (QUOTE IRONCLAD::XOR-BLOCK) (SB-INT:NAMED-LAMBDA IRONCLAD::XOR-BLOCK (IRONCLAD:BLOCK-LENGTH IRONCLAD::INPUT-BLOCK1 IRONCLAD::INPUT-BLOCK1-START IRONCLAD::INPUT-BLOCK..
  8: (SB-C::CONVERT-AND-MAYBE-COMPILE (SB-IMPL::%DEFUN (QUOTE IRONCLAD::XOR-BLOCK) (SB-INT:NAMED-LAMBDA IRONCLAD::XOR-BLOCK (IRONCLAD:BLOCK-LENGTH IRONCLAD::INPUT-BLOCK1 IRONCLAD::INPUT-BLOCK1-START IRONCL..
  9: ((FLET SB-C::DEFAULT-PROCESSOR :IN SB-C::PROCESS-TOPLEVEL-FORM) (SB-IMPL::%DEFUN (QUOTE IRONCLAD::XOR-BLOCK) (SB-INT:NAMED-LAMBDA IRONCLAD::XOR-BLOCK (IRONCLAD:BLOCK-LENGTH IRONCLAD::INPUT-BLOCK1 IRON..
 10: (SB-C::PROCESS-TOPLEVEL-FORM (SB-IMPL::%DEFUN (QUOTE IRONCLAD::XOR-BLOCK) (SB-INT:NAMED-LAMBDA IRONCLAD::XOR-BLOCK (IRONCLAD:BLOCK-LENGTH IRONCLAD::INPUT-BLOCK1 IRONCLAD::INPUT-BLOCK1-START IRONCLAD::..
 11: (SB-C::PROCESS-TOPLEVEL-PROGN ((EVAL-WHEN (:COMPILE-TOPLEVEL) (SB-C:%COMPILER-DEFUN # NIL T)) (SB-IMPL::%DEFUN (QUOTE IRONCLAD::XOR-BLOCK) (SB-INT:NAMED-LAMBDA IRONCLAD::XOR-BLOCK # # #) (SB-C:SOURCE-..
 12: (SB-C::PROCESS-TOPLEVEL-FORM (PROGN (EVAL-WHEN (:COMPILE-TOPLEVEL) (SB-C:%COMPILER-DEFUN # NIL T)) (SB-IMPL::%DEFUN (QUOTE IRONCLAD::XOR-BLOCK) (SB-INT:NAMED-LAMBDA IRONCLAD::XOR-BLOCK # # #) (SB-C:SO..
 13: ((FLET SB-C::DEFAULT-PROCESSOR :IN SB-C::PROCESS-TOPLEVEL-FORM) (DEFUN IRONCLAD::XOR-BLOCK (IRONCLAD:BLOCK-LENGTH IRONCLAD::INPUT-BLOCK1 IRONCLAD::INPUT-BLOCK1-START IRONCLAD::INPUT-BLOCK2 IRONCLAD::I..
 14: (SB-C::PROCESS-TOPLEVEL-FORM (DEFUN IRONCLAD::XOR-BLOCK (IRONCLAD:BLOCK-LENGTH IRONCLAD::INPUT-BLOCK1 IRONCLAD::INPUT-BLOCK1-START IRONCLAD::INPUT-BLOCK2 IRONCLAD::INPUT-BLOCK2-START IRONCLAD::OUTPUT-..
 15: ((LAMBDA (SB-KERNEL:FORM &KEY :CURRENT-INDEX &ALLOW-OTHER-KEYS) :IN SB-C::SUB-SUB-COMPILE-FILE) (DEFUN IRONCLAD::XOR-BLOCK (IRONCLAD:BLOCK-LENGTH IRONCLAD::INPUT-BLOCK1 IRONCLAD::INPUT-BLOCK1-START IR..
 16: (SB-C::%DO-FORMS-FROM-INFO #<FUNCTION (LAMBDA (SB-KERNEL:FORM &KEY :CURRENT-INDEX &ALLOW-OTHER-KEYS) :IN SB-C::SUB-SUB-COMPILE-FILE) {222D240B}> #<SB-C::SOURCE-INFO {100ACCC393}> SB-C::INPUT-ERROR-IN-..
 17: (SB-C::SUB-SUB-COMPILE-FILE #<SB-C::SOURCE-INFO {100ACCC393}>)
 18: ((FLET SB-THREAD::WITH-RECURSIVE-LOCK-THUNK :IN SB-C::SUB-COMPILE-FILE))
 19: ((FLET #:WITHOUT-INTERRUPTS-BODY-387 :IN SB-THREAD::CALL-WITH-RECURSIVE-LOCK))
 20: (SB-THREAD::CALL-WITH-RECURSIVE-LOCK #<CLOSURE (FLET SB-THREAD::WITH-RECURSIVE-LOCK-THUNK :IN SB-C::SUB-COMPILE-FILE) {7FFFF4E84AEB}> #<SB-THREAD:MUTEX "World Lock" owner: #<SB-THREAD:THREAD "repl-thr..
 21: ((LAMBDA NIL :IN SB-C::SUB-COMPILE-FILE))
 22: ((FLET SB-C::WITH-IT :IN SB-C::%WITH-COMPILATION-UNIT))
 23: (SB-C::SUB-COMPILE-FILE #<SB-C::SOURCE-INFO {100ACCC393}>)
 24: (COMPILE-FILE #P"/home/matt/quicklisp/dists/quicklisp/software/ironclad-v0.47/src/common.lisp" :OUTPUT-FILE #P"/home/matt/.cache/common-lisp/sbcl-1.3.14-linux-x64/home/matt/quicklisp/dists/quicklisp/s..
 25: (UIOP/UTILITY:CALL-WITH-MUFFLED-CONDITIONS #<CLOSURE (LAMBDA NIL :IN UIOP/LISP-BUILD:COMPILE-FILE*) {100ACC936B}> NIL)
 26: (UIOP/PATHNAME:CALL-WITH-ENOUGH-PATHNAME #P"/home/matt/quicklisp/dists/quicklisp/software/ironclad-v0.47/src/common.lisp" NIL #<CLOSURE (LAMBDA (UIOP/LISP-BUILD::INPUT-FILE) :IN UIOP/LISP-BUILD:COMPIL..
 27: (UIOP/LISP-BUILD:COMPILE-FILE* #P"/home/matt/quicklisp/dists/quicklisp/software/ironclad-v0.47/src/common.lisp" :OUTPUT-FILE #P"/home/matt/.cache/common-lisp/sbcl-1.3.14-linux-x64/home/matt/quicklisp/..
 28: (ASDF/LISP-ACTION:PERFORM-LISP-COMPILATION #<ASDF/LISP-ACTION:COMPILE-OP > #<IRONCLAD-SYSTEM::IRONCLAD-SOURCE-FILE "ironclad" "src" "common">)
 29: ((SB-PCL::EMF ASDF/ACTION:PERFORM) #<unavailable argument> #<unavailable argument> #<ASDF/LISP-ACTION:COMPILE-OP > #<IRONCLAD-SYSTEM::IRONCLAD-SOURCE-FILE "ironclad" "src" "common">)
 30: ((:METHOD ASDF/ACTION:PERFORM :AROUND (ASDF/LISP-ACTION:COMPILE-OP IRONCLAD-SYSTEM::IRONCLAD-SOURCE-FILE)) #<ASDF/LISP-ACTION:COMPILE-OP > #<IRONCLAD-SYSTEM::IRONCLAD-SOURCE-FILE "ironclad" "src" "com..
 31: ((:METHOD ASDF/ACTION:PERFORM-WITH-RESTARTS :AROUND (T T)) #<ASDF/LISP-ACTION:COMPILE-OP > #<IRONCLAD-SYSTEM::IRONCLAD-SOURCE-FILE "ironclad" "src" "common">) [fast-method]
 32: ((:METHOD ASDF/PLAN:PERFORM-PLAN (LIST)) ((#<ASDF/LISP-ACTION:COMPILE-OP > . #<ASDF/SYSTEM:SYSTEM "alexandria">) (#1=#<ASDF/LISP-ACTION:COMPILE-OP > . #2=#<IRONCLAD-SYSTEM::IRONCLAD-SOURCE-FILE #3="ir..
 33: ((FLET SB-C::WITH-IT :IN SB-C::%WITH-COMPILATION-UNIT))
 34: ((:METHOD ASDF/PLAN:PERFORM-PLAN :AROUND (T)) ((#<ASDF/LISP-ACTION:COMPILE-OP > . #<ASDF/SYSTEM:SYSTEM "alexandria">) (#1=#<ASDF/LISP-ACTION:COMPILE-OP > . #2=#<IRONCLAD-SYSTEM::IRONCLAD-SOURCE-FILE #..
 35: ((FLET SB-C::WITH-IT :IN SB-C::%WITH-COMPILATION-UNIT))
 36: ((:METHOD ASDF/PLAN:PERFORM-PLAN :AROUND (T)) #<ASDF/PLAN:SEQUENTIAL-PLAN {100A7A34D3}> :VERBOSE NIL) [fast-method]
 37: ((:METHOD ASDF/OPERATE:OPERATE (ASDF/OPERATION:OPERATION ASDF/COMPONENT:COMPONENT)) #<ASDF/LISP-ACTION:LOAD-OP :VERBOSE NIL> #<ASDF/SYSTEM:SYSTEM "ironclad"> :VERBOSE NIL) [fast-method]
 38: ((SB-PCL::EMF ASDF/OPERATE:OPERATE) #<unused argument> #<unused argument> #<ASDF/LISP-ACTION:LOAD-OP :VERBOSE NIL> #<ASDF/SYSTEM:SYSTEM "ironclad"> :VERBOSE NIL)
 39: ((LAMBDA NIL :IN ASDF/OPERATE:OPERATE))
 40: ((:METHOD ASDF/OPERATE:OPERATE :AROUND (T T)) #<ASDF/LISP-ACTION:LOAD-OP :VERBOSE NIL> #<ASDF/SYSTEM:SYSTEM "ironclad"> :VERBOSE NIL) [fast-method]
 41: ((SB-PCL::EMF ASDF/OPERATE:OPERATE) #<unused argument> #<unused argument> ASDF/LISP-ACTION:LOAD-OP "ironclad" :VERBOSE NIL)
 42: ((LAMBDA NIL :IN ASDF/OPERATE:OPERATE))
 43: (ASDF/CACHE:CALL-WITH-ASDF-CACHE #<CLOSURE (LAMBDA NIL :IN ASDF/OPERATE:OPERATE) {100A79407B}> :OVERRIDE NIL :KEY NIL)
 44: ((:METHOD ASDF/OPERATE:OPERATE :AROUND (T T)) ASDF/LISP-ACTION:LOAD-OP "ironclad" :VERBOSE NIL) [fast-method]
 45: ((:METHOD ASDF/OPERATE:OPERATE :AROUND (T T)) ASDF/LISP-ACTION:LOAD-OP "ironclad" :VERBOSE NIL) [fast-method]
 46: (ASDF/OPERATE:LOAD-SYSTEM "ironclad" :VERBOSE NIL)
 47: (QUICKLISP-CLIENT::CALL-WITH-MACROEXPAND-PROGRESS #<CLOSURE (LAMBDA NIL :IN QUICKLISP-CLIENT::APPLY-LOAD-STRATEGY) {100A78566B}>)
 48: (QUICKLISP-CLIENT::AUTOLOAD-SYSTEM-AND-DEPENDENCIES "ironclad" :PROMPT NIL)
 49: ((:METHOD QL-IMPL-UTIL::%CALL-WITH-QUIET-COMPILATION (T T)) #<unavailable argument> #<CLOSURE (FLET QUICKLISP-CLIENT::QL :IN QUICKLISP-CLIENT:QUICKLOAD) {100A76B17B}>) [fast-method]
 50: ((:METHOD QL-IMPL-UTIL::%CALL-WITH-QUIET-COMPILATION :AROUND (QL-IMPL:SBCL T)) #<QL-IMPL:SBCL {1001FFA013}> #<CLOSURE (FLET QUICKLISP-CLIENT::QL :IN QUICKLISP-CLIENT:QUICKLOAD) {100A76B17B}>) [fast-me..
 51: ((:METHOD QUICKLISP-CLIENT:QUICKLOAD (T)) #<unavailable argument> :PROMPT NIL :SILENT NIL :VERBOSE NIL) [fast-method]
 52: (QL-DIST::CALL-WITH-CONSISTENT-DISTS #<CLOSURE (LAMBDA NIL :IN QUICKLISP-CLIENT:QUICKLOAD) {100A760BEB}>)
 53: (SB-INT:SIMPLE-EVAL-IN-LEXENV (QUICKLISP-CLIENT:QUICKLOAD :IRONCLAD) #<NULL-LEXENV>)
 54: (EVAL (QUICKLISP-CLIENT:QUICKLOAD :IRONCLAD))
 55: (SWANK::EVAL-REGION "(ql:quickload :ironclad) ..)
 56: ((LAMBDA NIL :IN SWANK-REPL::REPL-EVAL))
 57: (SWANK-REPL::TRACK-PACKAGE #<CLOSURE (LAMBDA NIL :IN SWANK-REPL::REPL-EVAL) {100A760AAB}>)
 58: (SWANK::CALL-WITH-RETRY-RESTART "Retry SLIME REPL evaluation request." #<CLOSURE (LAMBDA NIL :IN SWANK-REPL::REPL-EVAL) {100A760A0B}>)
 59: (SWANK::CALL-WITH-BUFFER-SYNTAX NIL #<CLOSURE (LAMBDA NIL :IN SWANK-REPL::REPL-EVAL) {100A7609EB}>)`

Dependency version alarm bells ring because the nibbles version is 20180831-git. Any ideas?

**Comment by glv2** [comment]
According to the backtrace, you are using SBCL 1.3.14. which is pretty old.

You could try 3 things (any of them should solve the problem):
 - Update SBCL to a more recent version.
 - Use a version of Nibbles patched with https://github.com/sharplispers/nibbles/pull/6.
 - Use the master branch of Ironclad.

**Comment by glv2** [comment]
Ironclad 0.48 is now in quicklisp, so this issue should not happen anymore.
