### ISSUE TITLE
Why aren't key classes exported?

### ISSUE THREAD

**Issue by stylewarning** [sharplispers/ironclad#28]
I want to specialize GFs on key types, like private/public keys. Why isn't, for example, `IRONCLAD::RSA-PRIVATE-KEY` exported? Should consumers of these keys be agnostic to the kind of key?

**Comment by glv2** [comment]
The public/private key types could indeed be useful for users' generic functions.
Done in commit b37613704605685a8c80579ebfb18a5363232407.

**Comment by stylewarning** [comment]
Thanks! This is useful so that, for instance, a generic function can't accidentally accept a public key for signage, or a private key for verification.
