### ISSUE TITLE
ironcald:digest-supported-p doesn't work on the keyword

### ISSUE THREAD

**Issue by Yehouda** [sharplispers/ironclad#35]
**ironcald:digest-supported-p** returns true only on the **ironclad** symbol but not the keyword, which is not really useful because the keyword is the user visible one. Specially now that **ironclad:list-all-digests** returns the keywords (https://github.com/sharplispers/ironclad/commit/2139d2b8b703181701d2608357fdaf630c7f5711), calling **ironcald:digest-supported-p**  on the resulting symbols return nil.

Presumably just needs to call **massage-symbol** like **digest-length** does.

**Comment by glv2** [comment]
Fixed in 6209985d329748dbdcef987f656f79b3848d821d.

Thanks for the report.
