### ISSUE TITLE
Suggest AESX as Extended Rounds AES 

### ISSUE THREAD

**Issue by dbmcclain** [sharplispers/ironclad#4]
As per recommendations of Bruce Schneier, AESX (attached) implements AES encryption with extended rounds:
  For 128-bit keys use 16 rounds
  For 192-bit keys use 20 rounds
  For 256-bit keys use 28 rounds
To accomplish this the ROUND-CONSTANTS need to be extended in a group theoretic manner as shown by ROUNDX-CONSTANTS in the attached file.
[aesx.txt](https://github.com/sharplispers/ironclad/files/1605880/aesx.txt)

PACKAGES.lisp also needs to be extended with #:AESX alongside #:AES, and .ASD file needs to include "aesx" alongside "aes"

**Comment by glv2** [comment]
Do you know if there are some publications and test vectors for this cipher?

The only thing I found so far is Bruce Schneier's suggestion on his blog in 2009 (https://www.schneier.com/blog/archives/2009/07/another_new_aes.html).

**Comment by dbmcclain** [comment]
Hi glv2,

That’s all I ever had too. I did this work on AESX back in 2012. I have been using it every day since in my lab here. It seems to work, as it is built atop of existing AES. So sorry, I cannot help you with certified test vectors, unless you just want me to generate some from my machines here.

Cheers,

- DM

**Comment by glv2** [comment]
As this AESX cipher is apparently not used by any software, and there are neither articles published about it nor test vectors, I prefer not to put it in Ironclad.
