### ISSUE TITLE
Test suite running out of memory on i386/armhf/armel with SBCL 2.4.5

### ISSUE THREAD

**Issue by spwhitton** [sharplispers/ironclad#53]
Hello,

As can be seen on ci.debian.net, with SBCL 2.2.6 on [armhf](https://ci.debian.net/packages/c/cl-ironclad/testing/armhf/) and [armel](https://ci.debian.net/packages/c/cl-ironclad/testing/armel/) the ironclad test suite is running out of heap.  This didn't occur with SBCL 2.2.3, the most recent version included in Debian before 2.2.6.  I don't know whether the bug is in SBCL or ironclad.  Would be grateful if you could take a look.

Thanks.

**Comment by spwhitton** [comment]
This is now happening on i386 too, with sbcl 2.4.5.  Here is a backtrace:

    exhausted during allocation: 24576 bytes available, 32776 requested.
	    Immobile Object Counts
     Gen layout fdefn symbol   code  Boxed   Cons    Raw   Code  SmMix  Mixed  LgRaw LgCode  LgMix Waste%       Alloc        Trig   Dirty GCs Mem-age
      0      0      0      0      0      0      0      0      0      0      6      0      0   2862   11.1    10443144     5368709       -   0  0.0000
      1      0      0      0      0     70      7     11      0      4     21  43056      0      0   11.1   157244728   123298517   43072   1  0.7500
      2      0      0      0      0   8814   1426   1529     63    148    939  63127     46    362    9.9   282159120     5368709   64758   0  0.7397
      3      0      0      0      0    979    435    605    527    103    120     41    492    110    3.4    13493832    18862541    1051   1  0.0000
      4      0      0      0      0      0      0      0      0      0      0      0      0      0    0.0           0     2000000       0   0  0.0000
      5      0      0      0      0      0      0      0      0      0      0      0      0      0    0.0           0     2000000       0   0  0.0000
      6      0      0      0      0    905    440    303   2576    298     26      5     34    133    1.8    18993656     2000000     248   0  0.0000
    Tot      0      0      0      0  10768   2308   2448   3166    553   1112 106229    572   3467    9.8   482334480 [89.8% of 536870912 max]
    GC control variables:
       *GC-INHIBIT* = false
       *GC-PENDING* = false
       *STOP-FOR-GC-PENDING* = false
    Collection trigger variables:
       dynamic_space_size = 536870912
       bytes_allocated = 482334480
       auto_gc_trigger = 498734881
       bytes_consed_between_gcs = 26843545
    Unhandled SB-KERNEL::HEAP-EXHAUSTED-ERROR in thread #<SB-THREAD:THREAD tid=1202 "main thread" RUNNING
							   {96E7059}>:
      Heap exhausted (no more space for allocation).
    24576 bytes available, 32776 requested.

    PROCEED WITH CAUTION.

    Backtrace for: #<SB-THREAD:THREAD tid=1202 "main thread" RUNNING {96E7059}>
    0: (SB-DEBUG::DEBUGGER-DISABLED-HOOK #<SB-KERNEL::HEAP-EXHAUSTED-ERROR {90353C1}> #<unused argument> :QUIT T)
    1: (SB-DEBUG::RUN-HOOK SB-EXT:*INVOKE-DEBUGGER-HOOK* #<SB-KERNEL::HEAP-EXHAUSTED-ERROR {90353C1}>)
    2: (INVOKE-DEBUGGER #<SB-KERNEL::HEAP-EXHAUSTED-ERROR {90353C1}>)
    3: (ERROR #<SB-KERNEL::HEAP-EXHAUSTED-ERROR {90353C1}>)
    4: (SB-KERNEL::HEAP-EXHAUSTED-ERROR 6144 8194)
    5: ("foreign function: call_into_lisp")
    6: ("foreign function: funcall2")
    7: ("foreign function: gc_heap_exhausted_error_or_lose")
    8: ("foreign function: gc_find_freeish_pages")
    9: ("foreign function: gc_alloc_large")
    10: ("foreign function: alloc")
    11: (SB-VM::ALLOC-OVERFLOW-EBX)
    12: ("foreign function: #x28FDF007")
    13: (SB-C::COMPUTE-BLOCK-IN #<SB-C::CBLOCK 85 :START c1 {11F1DF79}> NIL)
    14: (SB-C::FIND-AND-PROPAGATE-CONSTRAINTS #<SB-C:COMPONENT :NAME "DEFUN ARGON2-G-ROUNDS" {B21B431}>)
    15: (SB-C::CONSTRAINT-PROPAGATE #<SB-C:COMPONENT :NAME "DEFUN ARGON2-G-ROUNDS" {B21B431}>)
    16: (SB-C::IR1-OPTIMIZE-PHASE-1 #<SB-C:COMPONENT :NAME "DEFUN ARGON2-G-ROUNDS" {B21B431}>)
    17: (SB-C::IR1-PHASES #<SB-C:COMPONENT :NAME "DEFUN ARGON2-G-ROUNDS" {B21B431}>)
    18: (SB-C::COMPILE-COMPONENT #<SB-C:COMPONENT :NAME "DEFUN ARGON2-G-ROUNDS" {B21B431}>)
    19: (SB-C::COMPILE-TOPLEVEL (#<SB-C::CLAMBDA :%SOURCE-NAME SB-C::.ANONYMOUS. :%DEBUG-NAME "top level form" :KIND (TOPLEVEL) :TYPE #<SB-KERNEL:BUILT-IN-CLASSOID FUNCTION (read-only)> :WHERE-FROM :DEFINED :VARS NIL {AB66D79}>) NIL)
    20: (SB-C::CONVERT-AND-MAYBE-COMPILE (SB-IMPL::%DEFUN (QUOTE ARGON2-G-ROUNDS) (SB-INT:NAMED-LAMBDA ARGON2-G-ROUNDS (WORK-BLOCK) (DECLARE (SB-C::TOP-LEVEL-FORM)) (DECLARE (TYPE ARGON2-BLOCK WORK-BLOCK)) (BLOCK ARGON2-G-ROUNDS (LOOP FOR I FROM 0 BELOW 128 BY 16 DO (ARGON2-ROUND # # # # # # # # # # # ...)) (LOOP FOR I FROM 0 BELOW 16 BY 2 DO (ARGON2-ROUND # # # # # # # # # # # ...)) (VALUES)))) (#1=(SB-IMPL::%DEFUN (QUOTE ARGON2-G-ROUNDS) (SB-INT:NAMED-LAMBDA ARGON2-G-ROUNDS (WORK-BLOCK) (DECLARE (SB-C::TOP-LEVEL-FORM)) (DECLARE (TYPE ARGON2-BLOCK WORK-BLOCK)) (BLOCK ARGON2-G-ROUNDS (LOOP FOR I FROM 0 BELOW 128 BY 16 DO #) (LOOP FOR I FROM 0 BELOW 16 BY 2 DO #) (VALUES)))) (PROGN (EVAL-WHEN (:COMPILE-TOPLEVEL) (SB-C:%COMPILER-DEFUN (QUOTE ARGON2-G-ROUNDS) T NIL NIL)) #1#) SB-C::ORIGINAL-SOURCE-START 0 14))
    21: (SB-C::PROCESS-TOPLEVEL-FORM (SB-IMPL::%DEFUN (QUOTE ARGON2-G-ROUNDS) (SB-INT:NAMED-LAMBDA ARGON2-G-ROUNDS (WORK-BLOCK) (DECLARE (SB-C::TOP-LEVEL-FORM)) (DECLARE (TYPE ARGON2-BLOCK WORK-BLOCK)) (BLOCK ARGON2-G-ROUNDS (LOOP FOR I FROM 0 BELOW 128 BY 16 DO (ARGON2-ROUND # # # # # # # # # # # ...)) (LOOP FOR I FROM 0 BELOW 16 BY 2 DO (ARGON2-ROUND # # # # # # # # # # # ...)) (VALUES)))) ((PROGN (EVAL-WHEN (:COMPILE-TOPLEVEL) (SB-C:%COMPILER-DEFUN (QUOTE ARGON2-G-ROUNDS) T NIL NIL)) (SB-IMPL::%DEFUN (QUOTE ARGON2-G-ROUNDS) (SB-INT:NAMED-LAMBDA ARGON2-G-ROUNDS (WORK-BLOCK) (DECLARE #) (DECLARE #) (BLOCK ARGON2-G-ROUNDS # # #)))) SB-C::ORIGINAL-SOURCE-START 0 14) NIL)
    22: (SB-C::PROCESS-TOPLEVEL-PROGN ((EVAL-WHEN (:COMPILE-TOPLEVEL) (SB-C:%COMPILER-DEFUN (QUOTE ARGON2-G-ROUNDS) T NIL NIL)) (SB-IMPL::%DEFUN (QUOTE ARGON2-G-ROUNDS) (SB-INT:NAMED-LAMBDA ARGON2-G-ROUNDS (WORK-BLOCK) (DECLARE (SB-C::TOP-LEVEL-FORM)) (DECLARE (TYPE ARGON2-BLOCK WORK-BLOCK)) (BLOCK ARGON2-G-ROUNDS (LOOP FOR I FROM 0 BELOW 128 BY 16 DO #) (LOOP FOR I FROM 0 BELOW 16 BY 2 DO #) (VALUES))))) ((PROGN (EVAL-WHEN (:COMPILE-TOPLEVEL) (SB-C:%COMPILER-DEFUN (QUOTE ARGON2-G-ROUNDS) T NIL NIL)) (SB-IMPL::%DEFUN (QUOTE ARGON2-G-ROUNDS) (SB-INT:NAMED-LAMBDA ARGON2-G-ROUNDS (WORK-BLOCK) (DECLARE #) (DECLARE #) (BLOCK ARGON2-G-ROUNDS # # #)))) SB-C::ORIGINAL-SOURCE-START 0 14) NIL)
    23: (SB-C::PROCESS-TOPLEVEL-FORM (PROGN (EVAL-WHEN (:COMPILE-TOPLEVEL) (SB-C:%COMPILER-DEFUN (QUOTE ARGON2-G-ROUNDS) T NIL NIL)) (SB-IMPL::%DEFUN (QUOTE ARGON2-G-ROUNDS) (SB-INT:NAMED-LAMBDA ARGON2-G-ROUNDS (WORK-BLOCK) (DECLARE (SB-C::TOP-LEVEL-FORM)) (DECLARE (TYPE ARGON2-BLOCK WORK-BLOCK)) (BLOCK ARGON2-G-ROUNDS (LOOP FOR I FROM 0 BELOW 128 BY 16 DO #) (LOOP FOR I FROM 0 BELOW 16 BY 2 DO #) (VALUES))))) (SB-C::ORIGINAL-SOURCE-START 0 14) NIL)
    24: (SB-C::PROCESS-TOPLEVEL-FORM (DEFUN ARGON2-G-ROUNDS (WORK-BLOCK) (DECLARE (TYPE ARGON2-BLOCK WORK-BLOCK)) (LOOP FOR I FROM 0 BELOW 128 BY 16 DO (ARGON2-ROUND (AREF WORK-BLOCK I) (AREF WORK-BLOCK (+ I 1)) (AREF WORK-BLOCK (+ I 2)) (AREF WORK-BLOCK (+ I 3)) (AREF WORK-BLOCK (+ I 4)) (AREF WORK-BLOCK (+ I 5)) (AREF WORK-BLOCK (+ I 6)) (AREF WORK-BLOCK (+ I 7)) (AREF WORK-BLOCK (+ I 8)) (AREF WORK-BLOCK (+ I 9)) (AREF WORK-BLOCK (+ I 10)) ...)) (LOOP FOR I FROM 0 BELOW 16 BY 2 DO (ARGON2-ROUND (AREF WORK-BLOCK I) (AREF WORK-BLOCK (+ I 1)) (AREF WORK-BLOCK (+ I 16)) (AREF WORK-BLOCK (+ I 17)) (AREF WORK-BLOCK (+ I 32)) (AREF WORK-BLOCK (+ I 33)) (AREF WORK-BLOCK (+ I 48)) (AREF WORK-BLOCK (+ I 49)) (AREF WORK-BLOCK (+ I 64)) (AREF WORK-BLOCK (+ I 65)) (AREF WORK-BLOCK (+ I 80)) ...)) (VALUES)) (SB-C::ORIGINAL-SOURCE-START 0 14) NIL)
    25: ((LAMBDA (SB-KERNEL:FORM &KEY :CURRENT-INDEX &ALLOW-OTHER-KEYS) :IN SB-C::SUB-COMPILE-FILE) (DEFUN ARGON2-G-ROUNDS (WORK-BLOCK) (DECLARE (TYPE ARGON2-BLOCK WORK-BLOCK)) (LOOP FOR I FROM 0 BELOW 128 BY 16 DO (ARGON2-ROUND (AREF WORK-BLOCK I) (AREF WORK-BLOCK (+ I 1)) (AREF WORK-BLOCK (+ I 2)) (AREF WORK-BLOCK (+ I 3)) (AREF WORK-BLOCK (+ I 4)) (AREF WORK-BLOCK (+ I 5)) (AREF WORK-BLOCK (+ I 6)) (AREF WORK-BLOCK (+ I 7)) (AREF WORK-BLOCK (+ I 8)) (AREF WORK-BLOCK (+ I 9)) (AREF WORK-BLOCK (+ I 10)) ...)) (LOOP FOR I FROM 0 BELOW 16 BY 2 DO (ARGON2-ROUND (AREF WORK-BLOCK I) (AREF WORK-BLOCK (+ I 1)) (AREF WORK-BLOCK (+ I 16)) (AREF WORK-BLOCK (+ I 17)) (AREF WORK-BLOCK (+ I 32)) (AREF WORK-BLOCK (+ I 33)) (AREF WORK-BLOCK (+ I 48)) (AREF WORK-BLOCK (+ I 49)) (AREF WORK-BLOCK (+ I 64)) (AREF WORK-BLOCK (+ I 65)) (AREF WORK-BLOCK (+ I 80)) ...)) (VALUES)) :CURRENT-INDEX 14)
    26: (SB-C::%DO-FORMS-FROM-INFO #<FUNCTION (LAMBDA (SB-KERNEL:FORM &KEY :CURRENT-INDEX &ALLOW-OTHER-KEYS) :IN SB-C::SUB-COMPILE-FILE) {9CCECA5}> #<SB-C::SOURCE-INFO {E200A89}> SB-C::INPUT-ERROR-IN-COMPILE-FILE)
    27: ((LAMBDA NIL :IN SB-C::SUB-COMPILE-FILE))
    28: ((FLET SB-C::WITH-IT :IN SB-C::%WITH-COMPILATION-UNIT))
    29: (SB-C::SUB-COMPILE-FILE #<SB-C::SOURCE-INFO {E200A89}> NIL)
    30: (COMPILE-FILE #P"/usr/share/common-lisp/source/ironclad/src/kdf/argon2.lisp" :OUTPUT-FILE #P"/tmp/autopkgtest-lxc.oxptmvlg/downtmp/autopkgtest_tmp/usr/share/common-lisp/source/ironclad/src/kdf/argon2-tmpDKBKLORG.fasl" :VERBOSE NIL :PRINT NIL :EXTERNAL-FORMAT :UTF-8 :PROGRESS NIL :TRACE-FILE NIL :BLOCK-COMPILE NIL :ENTRY-POINTS NIL :EMIT-CFASL NIL)
    31: (UIOP/UTILITY:CALL-WITH-MUFFLED-CONDITIONS #<FUNCTION (LAMBDA NIL :IN UIOP/LISP-BUILD:COMPILE-FILE*) {E200255}> NIL)
    32: (UIOP/PATHNAME:CALL-WITH-ENOUGH-PATHNAME #P"/usr/share/common-lisp/source/ironclad/src/kdf/argon2.lisp" NIL #<FUNCTION (LAMBDA (UIOP/LISP-BUILD::INPUT-FILE) :IN UIOP/LISP-BUILD:COMPILE-FILE*) {E1FFF0D}>)
    33: (UIOP/LISP-BUILD:COMPILE-FILE* #P"/usr/share/common-lisp/source/ironclad/src/kdf/argon2.lisp" :OUTPUT-FILE #P"/tmp/autopkgtest-lxc.oxptmvlg/downtmp/autopkgtest_tmp/usr/share/common-lisp/source/ironclad/src/kdf/argon2.fasl" :EXTERNAL-FORMAT :UTF-8 :WARNINGS-FILE NIL)
    34: (ASDF/LISP-ACTION:PERFORM-LISP-COMPILATION #<ASDF/LISP-ACTION:COMPILE-OP > #<ASDF/LISP-ACTION:CL-SOURCE-FILE "ironclad/kdf/argon2" "argon2">)
    35: ((SB-PCL::EMF ASDF/ACTION:PERFORM) #<unused argument> #<unused argument> #<ASDF/LISP-ACTION:COMPILE-OP > #<ASDF/LISP-ACTION:CL-SOURCE-FILE "ironclad/kdf/argon2" "argon2">)
    36: ((LAMBDA NIL :IN ASDF/ACTION:CALL-WHILE-VISITING-ACTION))
    37: ((:METHOD ASDF/ACTION:PERFORM-WITH-RESTARTS :AROUND (T T)) #<ASDF/LISP-ACTION:COMPILE-OP > #<ASDF/LISP-ACTION:CL-SOURCE-FILE "ironclad/kdf/argon2" "argon2">) [fast-method]
    38: ((:METHOD ASDF/PLAN:PERFORM-PLAN (T)) #<ASDF/PLAN:SEQUENTIAL-PLAN {B2E1F29}>) [fast-method]
    39: ((FLET SB-C::WITH-IT :IN SB-C::%WITH-COMPILATION-UNIT))
    40: ((:METHOD ASDF/PLAN:PERFORM-PLAN :AROUND (T)) #<ASDF/PLAN:SEQUENTIAL-PLAN {B2E1F29}>) [fast-method]
    41: ((:METHOD ASDF/OPERATE:OPERATE (ASDF/OPERATION:OPERATION ASDF/COMPONENT:COMPONENT)) #<ASDF/LISP-ACTION:LOAD-OP > #<ASDF/SYSTEM:SYSTEM "cl-postgres"> :PLAN-CLASS NIL :PLAN-OPTIONS NIL) [fast-method]
    42: ((SB-PCL::EMF ASDF/OPERATE:OPERATE) #<unused argument> #<unused argument> #<ASDF/LISP-ACTION:LOAD-OP > #<ASDF/SYSTEM:SYSTEM "cl-postgres">)
    43: ((LAMBDA NIL :IN ASDF/OPERATE:OPERATE))
    44: ((:METHOD ASDF/OPERATE:OPERATE :AROUND (T T)) #<ASDF/LISP-ACTION:LOAD-OP > #<ASDF/SYSTEM:SYSTEM "cl-postgres">) [fast-method]
    45: ((SB-PCL::EMF ASDF/OPERATE:OPERATE) #<unused argument> #<unused argument> ASDF/LISP-ACTION:LOAD-OP "cl-postgres")
    46: ((LAMBDA NIL :IN ASDF/OPERATE:OPERATE))
    47: ((:METHOD ASDF/OPERATE:OPERATE :AROUND (T T)) ASDF/LISP-ACTION:LOAD-OP "cl-postgres") [fast-method]
    48: (ASDF/SESSION:CALL-WITH-ASDF-SESSION #<FUNCTION (LAMBDA NIL :IN ASDF/OPERATE:OPERATE) {AE2F135}> :OVERRIDE T :KEY NIL :OVERRIDE-CACHE T :OVERRIDE-FORCING NIL)
    49: ((LAMBDA NIL :IN ASDF/OPERATE:OPERATE))
    50: (ASDF/SESSION:CALL-WITH-ASDF-SESSION #<FUNCTION (LAMBDA NIL :IN ASDF/OPERATE:OPERATE) {BA21215}> :OVERRIDE NIL :KEY NIL :OVERRIDE-CACHE NIL :OVERRIDE-FORCING NIL)
    51: ((:METHOD ASDF/OPERATE:OPERATE :AROUND (T T)) ASDF/LISP-ACTION:LOAD-OP "cl-postgres") [fast-method]
    52: (ASDF/OPERATE:LOAD-SYSTEM "cl-postgres")
    53: ((LAMBDA NIL :IN "/tmp/autopkgtest-lxc.oxptmvlg/downtmp/build.XV1/src/debian/tests/runtests.lisp"))
    54: (SB-INT:SIMPLE-EVAL-IN-LEXENV (LET ((UIOP/CONFIGURATION:*USER-CACHE* (UIOP/OS:GETENV "AUTOPKGTEST_TMP"))) (ASDF/OPERATE:LOAD-SYSTEM "cl-postgres") (ASDF/OPERATE:LOAD-SYSTEM "s-sql") (ASDF/OPERATE:LOAD-SYSTEM "postmodern") (ASDF/OPERATE:LOAD-SYSTEM "simple-date") (ASDF/OPERATE:LOAD-SYSTEM "simple-date/tests")) #<NULL-LEXENV>)
    55: (SB-EXT:EVAL-TLF (LET ((UIOP/CONFIGURATION:*USER-CACHE* (UIOP/OS:GETENV "AUTOPKGTEST_TMP"))) (ASDF/OPERATE:LOAD-SYSTEM "cl-postgres") (ASDF/OPERATE:LOAD-SYSTEM "s-sql") (ASDF/OPERATE:LOAD-SYSTEM "postmodern") (ASDF/OPERATE:LOAD-SYSTEM "simple-date") (ASDF/OPERATE:LOAD-SYSTEM "simple-date/tests")) 2 NIL)
    56: ((LABELS SB-FASL::EVAL-FORM :IN SB-INT:LOAD-AS-SOURCE) (LET ((UIOP/CONFIGURATION:*USER-CACHE* (UIOP/OS:GETENV "AUTOPKGTEST_TMP"))) (ASDF/OPERATE:LOAD-SYSTEM "cl-postgres") (ASDF/OPERATE:LOAD-SYSTEM "s-sql") (ASDF/OPERATE:LOAD-SYSTEM "postmodern") (ASDF/OPERATE:LOAD-SYSTEM "simple-date") (ASDF/OPERATE:LOAD-SYSTEM "simple-date/tests")) 2)
    57: ((LAMBDA (SB-KERNEL:FORM &KEY :CURRENT-INDEX &ALLOW-OTHER-KEYS) :IN SB-INT:LOAD-AS-SOURCE) (LET ((UIOP/CONFIGURATION:*USER-CACHE* (UIOP/OS:GETENV "AUTOPKGTEST_TMP"))) (ASDF/OPERATE:LOAD-SYSTEM "cl-postgres") (ASDF/OPERATE:LOAD-SYSTEM "s-sql") (ASDF/OPERATE:LOAD-SYSTEM "postmodern") (ASDF/OPERATE:LOAD-SYSTEM "simple-date") (ASDF/OPERATE:LOAD-SYSTEM "simple-date/tests")) :CURRENT-INDEX 2)
    58: (SB-C::%DO-FORMS-FROM-INFO #<FUNCTION (LAMBDA (SB-KERNEL:FORM &KEY :CURRENT-INDEX &ALLOW-OTHER-KEYS) :IN SB-INT:LOAD-AS-SOURCE) {F71C89A5}> #<SB-C::SOURCE-INFO {9185ED1}> SB-C::INPUT-ERROR-IN-LOAD)
    59: (SB-INT:LOAD-AS-SOURCE #<SB-SYS:FD-STREAM for "file /tmp/autopkgtest-lxc.oxptmvlg/downtmp/build.XV1/src/debian/tests/runtests.lisp" {9183AA1}> :VERBOSE NIL :PRINT NIL :CONTEXT "loading")
    60: ((LABELS SB-FASL::LOAD-STREAM-1 :IN LOAD) #<SB-SYS:FD-STREAM for "file /tmp/autopkgtest-lxc.oxptmvlg/downtmp/build.XV1/src/debian/tests/runtests.lisp" {9183AA1}> NIL)
    61: (SB-FASL::CALL-WITH-LOAD-BINDINGS #<FUNCTION (LABELS SB-FASL::LOAD-STREAM-1 :IN LOAD) {F71C8B95}> #<SB-SYS:FD-STREAM for "file /tmp/autopkgtest-lxc.oxptmvlg/downtmp/build.XV1/src/debian/tests/runtests.lisp" {9183AA1}> NIL #<SB-SYS:FD-STREAM for "file /tmp/autopkgtest-lxc.oxptmvlg/downtmp/build.XV1/src/debian/tests/runtests.lisp" {9183AA1}>)
    62: (LOAD #<SB-SYS:FD-STREAM for "file /tmp/autopkgtest-lxc.oxptmvlg/downtmp/build.XV1/src/debian/tests/runtests.lisp" {9183AA1}> :VERBOSE NIL :PRINT NIL :IF-DOES-NOT-EXIST :ERROR :EXTERNAL-FORMAT :DEFAULT)
    63: ((FLET SB-IMPL::LOAD-SCRIPT :IN SB-IMPL::PROCESS-SCRIPT) #<SB-SYS:FD-STREAM for "file /tmp/autopkgtest-lxc.oxptmvlg/downtmp/build.XV1/src/debian/tests/runtests.lisp" {9183AA1}>)
    64: ((FLET SB-UNIX::BODY :IN SB-IMPL::PROCESS-SCRIPT))
    65: ((FLET "WITHOUT-INTERRUPTS-BODY-" :IN SB-IMPL::PROCESS-SCRIPT))
    66: (SB-IMPL::PROCESS-SCRIPT "debian/tests/runtests.lisp")
    67: (SB-IMPL::TOPLEVEL-INIT)
    68: ((FLET SB-UNIX::BODY :IN SB-IMPL::START-LISP))
    69: ((FLET "WITHOUT-INTERRUPTS-BODY-3" :IN SB-IMPL::START-LISP))
    70: (SB-IMPL::%START-LISP)

    unhandled condition in --disable-debugger mode, quitting
    ; 
    ; compilation unit aborted
    ;   caught 2 fatal ERROR conditions

**Comment by glv2** [comment]
Above the backtrace there is:
```
Collection trigger variables:
   dynamic_space_size = 536870912
```
which indicates that SBCL is running with a dynamic space size of 512 MiB, which is probably too low for some Argon2 tests.
Starting SBCL with the ```--dynamic-space-size 1024``` or ```--dynamic-space-size 2048``` option to run the test suite should work.
