### ISSUE TITLE
Using format ~A to build a symbol name is wrong.

### ISSUE THREAD

**Issue by informatimago** [sharplispers/ironclad#57]
Using format ~A to build a symbol name is wrong, because ~A respects `*print-case*`.
Similarly, using `read-from-string` is bad, since it respects the *readtable* as configured at macro expansion time! Instead, using `concatenate` and `intern`:
eg. in `define-digest-registers`,  
```
  (let* ((struct-name (read-from-string (format nil "~A-~A" digest-name '#:regs)))
         (constructor (read-from-string (format nil "~A-~A" '#:initial struct-name)))
         (copier (read-from-string (format nil "%~A-~A" '#:copy struct-name)))
         (digest-fun (read-from-string (format nil "~A~A" digest-name '#:regs-digest)))
```
should be:
```
  (let* ((struct-name (intern (concatenate 'string (string digest-name) (string '#:-regs))))
         (constructor (intern (concatenate 'string (string '#:initial-) (string struct-name))))
         (copier      (intern (concatenate 'string (string '#:copy-) (string struct-name))))
         (digest-fun  (intern (concatenate 'string (string digest-name) (string '#:-regs-digest))))
```
and similarly elsewhere!

**Comment by informatimago** [comment]
Of course, factoring that into a function such as `alexandria:symbolicate`:
```
user> (let ((bar 'quux)) (alexandria:SYMBOLICATE 'foo- bar))
foo-quux
user> (symbol-name *)
"FOO-QUUX"
```

**Comment by informatimago** [comment]
[0001-Build-symbols-using-SYMBOLICATE.patch](https://github.com/sharplispers/ironclad/files/11762503/0001-Build-symbols-using-SYMBOLICATE.patch)

**Comment by glv2** [comment]
I added a few fixes to your patch for the tests to pass, and applied it (a3ad615a0ee1b418c2ccbc686b7a6c022c166fc8).
Thanks.

**Comment by informatimago** [comment]
Thank you.
