### ISSUE TITLE
pbkdf2-hash-password is very slow for me

### ISSUE THREAD

**Issue by spapas** [sharplispers/ironclad#79]
Hello I'm trying to use pbkdf2-hash-password but it is *very* slow for me. For example, running it like this:

```lisp
(time (ironclad:pbkdf2-hash-password (ironclad:ascii-string-to-byte-array "123")
                                     :salt (ironclad:ascii-string-to-byte-array "123")
                                     :digest 'ironclad:sha256
                                     :iterations 720000))
```

I'm getting 

```
  1.485 seconds of real time
  1.046875 seconds of total run time (1.000000 user, 0.046875 system)
  [ Real times consist of 0.047 seconds GC time, and 1.438 seconds non-GC time. ]
  [ Run times consist of 0.046 seconds GC time, and 1.001 seconds non-GC time. ]
  70.51% CPU
  4,448,958,207 processor cycles
  1,077,092,880 bytes consed
```

I'm using SBCL 2.4.9 on Windows 11 with the latest ironclad. Any idea if I'm doing something wrong and how can I improve the speed ? 

If I use less iterations the speed is improved however 720000 is the current standard (https://docs.djangoproject.com/en/5.1/releases/5.0/#django-contrib-auth)

TIA

**Comment by glv2** [comment]
PBKDF2 is a key derivation function. It is much slower than a hash function on purpose.
The parameters of key derivation functions (```iterations``` for PBKDF2) are usually set for the computation to take around one second of CPU time, to prevent an attacker from testing many passwords quickly.

**Comment by spapas** [comment]
So this is the correct usage? I can't make ironclad any faster?

**Comment by glv2** [comment]
Yes, it's the correct usage.
If you need it to be faster, you can either reduce the iteration count (easy solution), or improve the implementation of the hash function you use in the KDF (sha256 in your example) to make is faster (harder solution).

**Comment by spapas** [comment]
Thank you @glv2  I'll close then issue then!
